name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Configure Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: |
            --version
      - name: Build & Test (api + sample)
        run: |
          ./gradlew --stacktrace --no-daemon \
            :api:test \
            :processor:test \
            :processor:runtime:assembleDebug \
            :sample:app:assembleDebug \
            :sample:app:testDebugUnitTest
      - name: Upload sample debug build
        uses: actions/upload-artifact@v4
        with:
          name: sample-app-debug
          path: sample/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
